# Generated by Django 3.2.8 on 2021-10-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('description_short', models.TextField(blank=True, null=True)),
                ('description_long', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('feature_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.backgroundimage')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceEvent',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('EVALUATE_MONEY', 'Compare Player Money'), ('EVALUATE_ITEM', 'Compare Item in Player Inventory'), ('SKILL_CHECK', 'Compare Player Attribute')], max_length=20)),
                ('operator', models.CharField(blank=True, choices=[('===', 'Equals'), ('>=', 'Greater than or equal to'), ('<=', 'Less than or equal to'), ('>', 'Greater than'), ('<', 'Less than'), ('!=', 'Not equal to')], default='===', max_length=3, null=True)),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('call_on_failure', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conditional',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('EVALUATE_MONEY', 'Compare Player Money'), ('EVALUATE_ITEM', 'Compare Item in Player Inventory'), ('SKILL_CHECK', 'Compare Player Attribute')], max_length=20)),
                ('for_success', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IconImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_linked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalBoolean',
            fields=[
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.conditional')),
                ('value', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalInteger',
            fields=[
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.conditional')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalOperator',
            fields=[
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.conditional')),
                ('operator', models.CharField(blank=True, choices=[('===', 'Equals'), ('>=', 'Greater than or equal to'), ('<=', 'Less than or equal to'), ('>', 'Greater than'), ('<', 'Less than'), ('!=', 'Not equal to')], default='===', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SceneNode',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('display_text', models.TextField()),
                ('display_text_visited', models.TextField(blank=True, null=True)),
                ('background_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.backgroundimage')),
                ('scene_linked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.scene')),
            ],
        ),
        migrations.CreateModel(
            name='NodeChoice',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('display_text', models.CharField(blank=True, max_length=200, null=True)),
                ('can_repeat', models.BooleanField(default=True)),
                ('has_condition', models.BooleanField(default=False)),
                ('can_fail', models.BooleanField(default=False)),
                ('hide_on_condition_fail', models.BooleanField(default=True)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('result_text_on_fail', models.TextField(blank=True, null=True)),
                ('icon_linked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.iconimage')),
                ('scene_node_linked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.scenenode')),
            ],
        ),
        migrations.AddField(
            model_name='conditional',
            name='choice_linked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.scene'),
        ),
    ]
