# Generated by Django 3.2.8 on 2021-10-12 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('description_short', models.TextField(blank=True, null=True)),
                ('description_long', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('feature_image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceEvent',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('EVALUATE_MONEY', 'Compare Player Money'), ('EVALUATE_ITEM', 'Compare Item in Player Inventory'), ('SKILL_CHECK', 'Compare Player Attribute')], max_length=20)),
                ('operator', models.CharField(blank=True, choices=[('===', 'Equals'), ('>=', 'Greater than or equal to'), ('<=', 'Less than or equal to'), ('>', 'Greater than'), ('<', 'Less than'), ('!=', 'Not equal to')], default='===', max_length=3, null=True)),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('callOnFailure', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('campaignLinked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='SceneNode',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('backgroundImage', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('displayText', models.TextField()),
                ('displayTextVisited', models.TextField(blank=True, null=True)),
                ('sceneLinked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.scene')),
            ],
        ),
        migrations.CreateModel(
            name='NodeChoice',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('displayText', models.CharField(blank=True, max_length=200, null=True)),
                ('canRepeat', models.BooleanField(default=True)),
                ('hasCondition', models.BooleanField(default=False)),
                ('canFail', models.BooleanField(default=False)),
                ('hideOnConditionFail', models.BooleanField(default=True)),
                ('resultText', models.TextField(blank=True, null=True)),
                ('resultTextOnFail', models.TextField(blank=True, null=True)),
                ('sceneNodeLinked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Conditional',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('EVALUATE_MONEY', 'Compare Player Money'), ('EVALUATE_ITEM', 'Compare Item in Player Inventory'), ('SKILL_CHECK', 'Compare Player Attribute')], max_length=20)),
                ('choiceLinked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.scene')),
            ],
        ),
    ]
