# Generated by Django 3.2.8 on 2021-10-12 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalBoolean',
            fields=[
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.conditional')),
                ('value', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalInteger',
            fields=[
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.conditional')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalOperator',
            fields=[
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.conditional')),
                ('operator', models.CharField(blank=True, choices=[('===', 'Equals'), ('>=', 'Greater than or equal to'), ('<=', 'Less than or equal to'), ('>', 'Greater than'), ('<', 'Less than'), ('!=', 'Not equal to')], default='===', max_length=3, null=True)),
            ],
        ),
    ]
