# Generated by Django 3.2.8 on 2021-10-17 07:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20211017_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
