# Generated by Django 3.2.8 on 2021-10-13 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_conditionalboolean_conditionalinteger_conditionaloperator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choiceevent',
            old_name='callOnFailure',
            new_name='call_on_failure',
        ),
        migrations.RenameField(
            model_name='conditional',
            old_name='choiceLinked',
            new_name='choice_linked',
        ),
        migrations.RenameField(
            model_name='nodechoice',
            old_name='canFail',
            new_name='can_fail',
        ),
        migrations.RenameField(
            model_name='nodechoice',
            old_name='canRepeat',
            new_name='can_repeat',
        ),
        migrations.RenameField(
            model_name='nodechoice',
            old_name='displayText',
            new_name='display_text',
        ),
        migrations.RenameField(
            model_name='nodechoice',
            old_name='hasCondition',
            new_name='has_condition',
        ),
        migrations.RenameField(
            model_name='nodechoice',
            old_name='hideOnConditionFail',
            new_name='hide_on_condition_fail',
        ),
        migrations.RenameField(
            model_name='nodechoice',
            old_name='resultText',
            new_name='result_text',
        ),
        migrations.RenameField(
            model_name='nodechoice',
            old_name='resultTextOnFail',
            new_name='result_text_on_fail',
        ),
        migrations.RenameField(
            model_name='scene',
            old_name='campaignLinked',
            new_name='campaign_linked',
        ),
        migrations.RenameField(
            model_name='scenenode',
            old_name='backgroundImage',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='scenenode',
            old_name='displayText',
            new_name='display_text',
        ),
        migrations.RenameField(
            model_name='scenenode',
            old_name='displayTextVisited',
            new_name='display_text_visited',
        ),
        migrations.RenameField(
            model_name='scenenode',
            old_name='sceneLinked',
            new_name='scene_linked',
        ),
        migrations.RemoveField(
            model_name='nodechoice',
            name='sceneNodeLinked',
        ),
        migrations.AddField(
            model_name='nodechoice',
            name='scene_node_linked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.scenenode'),
        ),
    ]
