# Generated by Django 3.2.8 on 2021-10-28 23:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20211025_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='description_short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iconimage',
            name='description_short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='iconimage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
