# Generated by Django 3.2.8 on 2021-10-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20211028_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenenode',
            name='name',
            field=models.CharField(default='scene', max_length=200),
            preserve_default=False,
        ),
    ]
